name: culinarymap
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - altair=5.0.1
  - folium=0.14.0
  - cryptography=43.0.3
  - pandas=2.2.3
  - numpy=1.26.4
  - pillow=11.1.0
  - requests=2.32.3
  - streamlit=1.41.1
  - pydeck=0.9.1
  - pip:
      - streamlit-folium
      - toml
      - streamlit-geolocation
